### ISSUE TITLE
Can't get server to show up

### ISSUE THREAD

**Issue by SLGShark6** [Johnny-Knighten/ark-sa-server#23]
First of all thank you for this amazingly comprehensive docker implementation. However, using the basic docker compose example:
```                                                                                     
version: '3'
services:
  ark-sa:
    container_name: ark
    image: johnnyknighten/ark-sa-server:latest
    restart: unless-stopped
    environment:
      - SERVER_NAME="SLG Park"
      - ADMIN_PASSWORD=
    volumes:
      - './server:/ark-server/server'
      - './backups:/ark-server/backups'
      - './logs:/ark-server/logs'
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27015:27015/udp
      - 27020:27020/tcp
 ```

Running on an external AlmaLinux 9.3 server. Have the ports opened in firewalld with a service definition:
/etc/firewalld/services/ark-server.xml 
```
?xml version="1.0" encoding="utf-8"?>
<service>
  <short>ark-server</short>
  <description>Ark Survival Ascended Game Server Ports</description>
  <port protocol="udp" port="7777"/>
  <port protocol="udp" port="7778"/>
  <port protocol="udp" port="27015"/>
  <port protocol="tcp" port="27020"/>
</service>
```
And it added to my network zone:
```
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: wg0
  sources: 
  services: ark-server
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
And server seems to startup fine:
![image](https://github.com/Johnny-Knighten/ark-sa-server/assets/35613914/1631c946-a098-442a-ab70-646cf8434def)

But can't find the server trying to connect on https://ark-servers.net:
![image](https://github.com/Johnny-Knighten/ark-sa-server/assets/35613914/08ff082f-fdb4-4f1f-adc8-2c56f4896156)

But connecting with a sibling server it seems to make a connection on the ports:
![image](https://github.com/Johnny-Knighten/ark-sa-server/assets/35613914/b460e565-108c-4878-89bf-75619e7e4b1e)

And Checking externally it shows open:
![image](https://github.com/Johnny-Knighten/ark-sa-server/assets/35613914/8e00639f-3336-4280-9350-bc281995dfed)

But nothing in ark either, after having the server running for 20 minutes:
![image](https://github.com/Johnny-Knighten/ark-sa-server/assets/35613914/a92977db-a416-4c54-beee-cc37c9c4917d)

So I'm not sure what I've done wrong or need to do.
